# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.21.3
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# You should use environment vars (https://marketplace.visualstudio.com/items?itemName=humao.rest-client#environment-variables) for these
# but you can also set here if needed (just don't check in!)

#@baseUrl = http://openevse.local

#@ssid = your_ssid
#@pass = your_password
#@apikey = your_key

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=true&tz=GMT0BST,M3.5.0/1,M10.5.0

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=true&tz=EST5EDT,M3.2.0,M11.1.0

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=true&tz=<+06>-6
###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=true&tz=Europe/Paris|CET-1CEST,M3.5.0,M10.5.0/3

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=false&time=2018-08-10T14:30:00Z&tz=GMT0BST,M3.5.0/1,M10.5.0

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

time=2018-08-10T14:30:00Z&tz=GMT0BST,M3.5.0/1,M10.5.0

###
# Invalid, should return error

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

time=20180810T143000Z

###
