# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.21.3
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# You should use environment vars (https://marketplace.visualstudio.com/items?itemName=humao.rest-client#environment-variables) for these
# but you can also set here if needed (just don't check in!)

#@baseUrl = http://openevse.local

#@ssid = your_ssid
#@pass = your_password
#@apikey = your_key

###

# @name config
GET {{baseUrl}}/config HTTP/1.1

###

GET {{baseUrl}}/update

###

POST {{baseUrl}}/update
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firmware"; filename="firmware.bin"
Content-Type: application/octet-stream

< ./.pio/build/{{config.response.body.buildenv}}/firmware.bin
----WebKitFormBoundary7MA4YWxkTrZu0gW

###

curl -F firmware=@.pio/build/openevse_esp-wrover-kit/firmware.bin {{baseUrl}}/update

###

# @name latest
GET https://api.github.com/repos/OpenEVSE/ESP32_WiFi_V4.x/releases/latest
Accept: application/vnd.github.v3+json

###

POST {{baseUrl}}/update
Content-Type: application/javascript

{
  "url": "{{latest.response.body.assets[1].browser_download_url}}"
}

###

POST {{baseUrl}}/update
Content-Type: application/javascript

{
  "url": "http://frenzy.lan:8000/.pio/build/{{config.response.body.buildenv}}/firmware.bin"
}
