# Name: REST Client
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.21.3
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# You should use environment vars (https://marketplace.visualstudio.com/items?itemName=humao.rest-client#environment-variables) for these
# but you can also set here if needed (just don't check in!)

#@baseUrl = http://openevse.local

#@ssid = your_ssid
#@pass = your_password
#@apikey = your_key

###

GET {{baseUrl}}/ HTTP/1.1

###

GET {{baseUrl}}/status HTTP/1.1

###

GET {{baseUrl}}/config HTTP/1.1

###

POST {{baseUrl}}/config HTTP/1.1
Content-Type: application/json

{
  "emoncms_enabled": true,
  "emoncms_server": "http://emoncms.org",
  "emoncms_node": "openevse-a7d4",
  "emoncms_apikey": "_DUMMY_PASSWORD",
  "emoncms_fingerprint": ""
}

###

POST {{baseUrl}}/config HTTP/1.1
Content-Type: application/json

{
  "emoncms_enabled": false
}

###

POST {{baseUrl}}/config HTTP/1.1
Content-Type: application/json

{
  "divert_enabled": true,
  "divert_attack_smoothing_factor": 0.4,
  "divert_decay_smoothing_factor": 0.05,
  "divert_min_charge_time": 60
}

###

POST {{baseUrl}}/config HTTP/1.1
Content-Type: application/json

{
  "divert_enabled": false
}

###

POST {{baseUrl}}/config HTTP/1.1
Content-Type: application/json

{
  "mqtt_enabled": true,
  "mqtt_protocol": "mqtt",
  "mqtt_server": "home.lan",
  "mqtt_port": 1883,
  "mqtt_topic": "openevse",
  "mqtt_user": "emonpi",
  "mqtt_pass": "_DUMMY_PASSWORD",
  "mqtt_solar": "",
  "mqtt_grid_ie": "emon/test/grid_ie",
  "mqtt_announce_topic": "openevse/announce/a7d4"
}

###

GET {{baseUrl}}/home.js HTTP/1.1

###

GET {{baseUrl}}/lib.js HTTP/1.1

###

GET {{baseUrl}}/wifi_signal_4.svg HTTP/1.1

###

GET {{baseUrl}}/zones.json HTTP/1.1

###

POST {{baseUrl}}/savenetwork HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ssid={{ssid}}&pass={{pass}}

###

POST {{baseUrl}}/saveemoncms HTTP/1.1
Content-Type: application/x-www-form-urlencoded


###

POST {{baseUrl}}/savemqtt HTTP/1.1
Content-Type: application/x-www-form-urlencoded


###

POST {{baseUrl}}/saveadmin HTTP/1.1
Content-Type: application/x-www-form-urlencoded


###

POST {{baseUrl}}/saveohmkey HTTP/1.1
Content-Type: application/x-www-form-urlencoded



###

POST {{baseUrl}}/savesntp HTTP/1.1
Content-Type: application/x-www-form-urlencoded

enable=false

###

GET {{baseUrl}}/reset HTTP/1.1

###

GET {{baseUrl}}/restart HTTP/1.1

###

GET {{baseUrl}}/rapi HTTP/1.1

###

GET {{baseUrl}}/r HTTP/1.1

###

GET {{baseUrl}}/r?json&rapi=$GS HTTP/1.1

###

GET {{baseUrl}}/r?json=1&rapi=$GS HTTP/1.1

###

GET {{baseUrl}}/r?json=0&rapi=$GS HTTP/1.1

###

GET {{baseUrl}}/r?rapi=$GS HTTP/1.1

###
# TODO

GET {{baseUrl}}/r?rapi=$GS HTTP/1.1
Accept: application/json

###
# TODO

POST {{baseUrl}}/r HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

rapi=$GS

###

GET {{baseUrl}}/r?json&rapi=$GV HTTP/1.1

###

GET {{baseUrl}}/scan HTTP/1.1

###

POST {{baseUrl}}/apoff HTTP/1.1

###

POST {{baseUrl}}/divertmode HTTP/1.1

###

GET {{baseUrl}}/emoncms/describe HTTP/1.1

###

GET {{baseUrl}}/r?json=1&rapi=$S1+19+9+9+10+4+29 HTTP/1.1

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=true&tz=GMT0BST,M3.5.0/1,M10.5.0

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=true&tz=EST5EDT,M3.2.0,M11.1.0

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=true&tz=<+06>-6
###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=true&tz=Europe/Paris|CET-1CEST,M3.5.0,M10.5.0/3

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

ntp=false&time=2018-08-10T14:30:00Z&tz=GMT0BST,M3.5.0/1,M10.5.0

###

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

time=2018-08-10T14:30:00Z&tz=GMT0BST,M3.5.0/1,M10.5.0

###
# Invalid, should return error

POST {{baseUrl}}/settime HTTP/1.1
Content-Type: application/x-www-form-urlencoded

time=20180810T143000Z

###
