static const char CONTENT_WIFI_PORTAL_HTML[] PROGMEM = 
  "<!doctype html> <html lang=\"en\"> <head> <meta charset=\"utf-8\"> <title>OpenEVSE</title> <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"> <meta name=\"viewport\" content=\"width=device-width,user-scalable=no\"> <meta name=\"description\" content=\"OpenEVSE\"> <meta name=\"author\" content=\"OpenEVSE\"> <meta name=\"theme-color\" content=\"#000000\"> <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"> <link rel=\"icon\" type=\"image/png\" href=\"favicon-32x32.png\" sizes=\"32x32\"> <link rel=\"icon\" type=\"image/png\" href=\"favicon-16x16.png\" sizes=\"16x16\"> </head> <body> <div id=\"page\"> <div class=\"header\"> <h1>Open<span>EVSE</span></h1> <h3>WiFi</h3> </div> <div class=\"container\" data-bind=\"visible: !initialised()\"> Loading, please wait... </div> <div class=\"container\" data-bind=\"visible: initialised\" style=\"display: none\"> <div data-bind=\"visible: status.isError\" class=\"box error\"> <h4>EVSE Error</h4> <span data-bind=\"text: status.estate\"></span> </div> <div data-bind=\"visible: !status.evse_connected()\" class=\"box error\"> <h4>EVSE Error</h4> <span>OpenEVSE not responding or not connected</span> </div> <div data-bind=\"visible: !status.isError() &amp;&amp; status.evse_connected(),\n"
  "                      css: { ready: status.isReady(),\n"
  "                              connected: status.isConnected() &amp;&amp; !status.isCharging(),\n"
  "                              charging: status.isCharging(),\n"
  "                              sleeping: status.isPaused() &amp;&amp; 0 == status.vehicle(),\n"
  "                              sleeping_connected: status.isPaused() &amp;&amp; 1 == status.vehicle() }\" class=\"box\"> <h2 class=\"left\">Status</h2> <h2 class=\"right\" data-bind=\"text: status.estate\"></h2> <table> <tr> <th>Current</th> <th>Energy</th> <th>Temp</th> <th>Elapsed</th> </tr> <tr> <td><span data-bind=\"text: scaleString(status.amp(), 1000, 2) + ' A'\"></span></td> <td><span data-bind=\"text: scaleString(status.session_energy(), 1000, 2) + ' kWh'\"></span></td> <td><span data-bind=\"text: scaleString(status.temp(), 10, 1) + ' &deg;C'\"></span></td> <td><span data-bind=\"text: time.elapsed\"></span></td> </tr> </table> </div> <div class=\"box\" data-bind=\"visible: status.evse_connected\"> <h2>Setup</h2> <p> <b>Service Level:</b><br> <select data-bind=\"options: serviceLevels,\n"
  "                             optionsText: 'name',\n"
  "                             optionsValue: 'value',\n"
  "                             value: config.service,\n"
  "                             disable: openEvseService.fetching,\n"
  "                             css: { saved: openEvseService.success }\"></select> </p> <p> <b>Max Current:</b><br> <select data-bind=\"options: currentLevels,\n"
  "                              optionsText: 'name',\n"
  "                              optionsValue: 'value',\n"
  "                              value: config.max_current_soft,\n"
  "                              disable: openEvseMaxCurrentSoft.fetching,\n"
  "                              css: { saved: openEvseMaxCurrentSoft.success }\"></select> </p> </div> <div class=\"box\" data-bind=\"visible: wifi.canConfigure() &amp;&amp; !wifi.wifiConnecting()\"> <h2>WiFi Setup</h2> <p><b>Mode:</b> <span id=\"mode\" data-bind=\"text: status.fullMode\"></span></p> <p>Connect to network:</p> <div id=\"wifiList\"> <ul class=\"list-group\" data-bind=\"foreach: scan.filteredResults, visible: 0 != scan.results().length\"> <li class=\"list-group-item\" data-bind=\"click: $root.wifi.select, css: { active: $root.wifi.selectedNet() === $data }\"> <span data-bind=\"text: ssid\"></span> <img width=\"24px\" height=\"24px\" data-bind=\"attr:{src: 'wifi_signal_'+strength()+'.svg'}\"> </li> </ul> </div> <div data-bind=\"visible: 0 == scan.results().length\"> Scanning... </div> <p> <b>SSID:</b><br> <input type=\"text\" autocapitalize=\"none\" data-bind=\"textInput: config.ssid\"> </p> <p> <b>Passkey:</b><br> <input type=\"text\" autocapitalize=\"none\" data-bind=\"textInput: wifiPassword.value, attr: { type: wifiPassword.show() ? 'text' : 'password' }\"><br> </p><div> <input id=\"wifipassword\" type=\"checkbox\" data-bind=\"checked: wifiPassword.show\"> <label for=\"wifipassword\">Show password</label> </div> <p></p> <p> <button data-bind=\"click: wifi.saveNetwork, text: (wifi.saveNetworkFetching() ? 'Saving' : (wifi.saveNetworkSuccess() ? 'Saved' : 'Connect')), disable: wifi.saveNetworkFetching\">Connect</button> </p> <p>Connecting to a local WiFi network is not essential. OpenEVSE can be configured and controlled while in standalone WiFi AP (Access Point) mode:</p> <div> <button onclick=\"window.location.href='/home.html'\">WiFi Standalone Mode</button> </div> <p><i><span class=\"small-text\">Note: remote logging features e.g Emoncms will not work while in AP standalone mode</span></i></p> </div> <div class=\"box\" data-bind=\"visible: wifi.wifiConnecting() || !wifi.canConfigure()\"> <h2>Connecting to <span data-bind=\"text: config.ssid\"></span> ...</h2> <p>Please connect this device to <span data-bind=\"text: config.ssid\"></span> and navigate to the IP address displayed on your OpenEVSE display.</p> <p>Alternatively you can use <a data-bind=\"attr: { href: 'http://' + config.hostname() + '.local/' }, text: 'http://' + config.hostname() + '.local/'\"></a> or <a data-bind=\"attr: { href: 'http://' + config.hostname() + '/' }, text: 'http://' + config.hostname() + '/'\"></a></p> <div id=\"client-view\" data-bind=\"visible: status.isWifiClient\"> <button id=\"apoff\" data-bind=\"click: wifi.turnOffAccessPoint, disable: wifi.turnOffAccessPointFetching\">Continue</button> </div> </div> <div id=\"footer\"> <br><b> Powered by <a href=\"http://www.com\">OpenEVSE</a> and <a href=\"https://openenergymonitor.org\">OpenEnergyMonitor</a></b> <br> <b>Version: </b>V<span data-bind=\"text: config.version\"></span> </div> </div> </div> <script src=\"lib.js\"></script> <script src=\"wifi_portal.js\"></script> </body> </html> \n";
static const char CONTENT_WIFI_PORTAL_HTML_ETAG[] PROGMEM = "1a99b5a4a2bf828696dec2d7c4afdb9ee68e434dc896eb8b2b1db3747e04a6a7";
