// Rasterise the OpenEVSE charge point mark into LVGL 8-bit alpha masks.
//
// The mark has two colour roles: the enclosure and cord follow the theme accent,
// the bolt is fixed violet. A single baked RGB bitmap would freeze both and break
// the panel's dark/light themes, so it is split into two LV_IMG_CF_ALPHA_8BIT
// masks. LVGL draws an A8 image entirely in the style's img_recolor, so each mask
// is tinted at draw time and both follow ns_set_theme() for free.
//
// One byte per pixel, so a 64x64 mask is 4 KB of flash and nothing at runtime --
// lv_img reads straight from the const array.
//
//   node scripts/gen_lvgl_mark.mjs
//
// Reads gui-nightshift/src/assets/mark.svg so the panel and the web UI cannot
// drift apart silently. Writes src/lvgl_tft/mark_img.c.

import sharp from '../gui-nightshift/node_modules/sharp/dist/index.mjs'
import { readFileSync, writeFileSync } from 'node:fs'

// 64 px is the floor for this artwork, not a layout preference: the cord is a
// 4.5 stroke in a 100-unit viewBox, so it lands at 2.9 device pixels here. Go
// much smaller and it drops under two pixels and greys out on a panel with no
// subpixel help. Do NOT scale at runtime -- LVGL's image transform would eat it.
const SIZE = 80

const SRC = new URL('../gui-nightshift/src/assets/mark.svg', import.meta.url)
const OUT = new URL('../src/lvgl_tft/mark_img.c', import.meta.url)

// Pull the three shapes out of the shared SVG rather than restating them, so a
// change to the mark reaches the panel by re-running this script.
const svg = readFileSync(SRC, 'utf8')
const shapes = svg.match(/<(?:rect|path)\b[^>]*\/>/g)
if (!shapes || shapes.length < 2) {
  throw new Error(`expected at least 2 shapes in mark.svg, found ${shapes ? shapes.length : 0}`)
}

// Split by colour role, not by position: the mark has gained shapes before (a
// second cord, the plug head) and will again. Anything painted currentColor is
// the shell and follows the theme; the bolt is whatever carries the fixed
// --mark-bolt violet.
const shell = shapes.filter((s) => s.includes('currentColor'))
const boltShapes = shapes.filter((s) => !s.includes('currentColor'))
if (shell.length === 0 || boltShapes.length === 0) {
  throw new Error(`mark.svg has ${shell.length} shell and ${boltShapes.length} bolt shapes; expected both`)
}

// currentColor has no meaning outside a document; the fill/stroke colour is
// irrelevant anyway because only the alpha channel survives.
const solid = (s) => s.replace(/currentColor/g, '#000')

const wrap = (body) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="${SIZE}" height="${SIZE}">${body}</svg>`

async function alphaOf(body) {
  const { data, info } = await sharp(Buffer.from(wrap(body)))
    .resize(SIZE, SIZE)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })

  const out = Buffer.alloc(SIZE * SIZE)
  for (let i = 0; i < SIZE * SIZE; i++) {
    out[i] = data[i * info.channels + (info.channels - 1)]
  }
  return out
}

function emit(name, bytes) {
  let s = `static const uint8_t ${name}_map[] = {\n`
  for (let i = 0; i < bytes.length; i += 16) {
    s += '  ' + [...bytes.subarray(i, i + 16)].map((b) => `0x${b.toString(16).padStart(2, '0')}`).join(', ') + ',\n'
  }
  s += '};\n\n'
  s += `const lv_img_dsc_t ${name} = {\n`
  s += `  .header = { .cf = LV_IMG_CF_ALPHA_8BIT, .always_zero = 0, .reserved = 0,\n`
  s += `              .w = ${SIZE}, .h = ${SIZE} },\n`
  s += `  .data_size = sizeof(${name}_map),\n`
  s += `  .data = ${name}_map,\n`
  s += `};\n\n`
  return s
}

const shellA = await alphaOf(shell.map(solid).join(''))
const boltA = await alphaOf(boltShapes.map(solid).join(''))

let out = `// GENERATED by scripts/gen_lvgl_mark.mjs -- do not edit by hand.\n`
out += `// Source: gui-nightshift/src/assets/mark.svg, rasterised at ${SIZE}x${SIZE}.\n`
out += `//\n`
out += `// Two 8-bit alpha masks, not one bitmap: the enclosure and cord are tinted with\n`
out += `// the theme accent and the bolt with the brand violet, so the mark follows\n`
out += `// ns_set_theme(). Callers MUST set both img_recolor and img_recolor_opa --\n`
out += `// LVGL only reads the colour when the opa is above zero and otherwise draws\n`
out += `// the mask in black (lv_obj_draw.c, lv_obj_init_draw_img_dsc).\n`
out += `#ifdef ENABLE_SCREEN_LVGL_TFT\n\n`
out += `#include <lvgl.h>\n\n`
out += `#include "mark_img.h"\n\n`
out += emit('mark_shell_img', shellA)
out += emit('mark_bolt_img', boltA)
out += `#endif // ENABLE_SCREEN_LVGL_TFT\n`

writeFileSync(OUT, out)
console.log(`wrote ${OUT.pathname}: 2 x ${SIZE}x${SIZE} A8 (${SIZE * SIZE} B each)`)
