static const char CONTENT_WIFI_PORTAL_JS[] PROGMEM = 
  "(function(){function d(a,b,c){c=void 0===c?{}:c;this.remoteUrl=b;ko.mapping.fromJS(a,c,this);this.fetching=ko.observable(!1)}function e(){var a=this;d.call(a,{mode:\"ERR\",srssi:\"\",ipaddress:\"\",packets_sent:\"\",packets_success:\"\",emoncms_connected:\"\",mqtt_connected:\"\",ohm_hour:\"\",free_heap:\"\"},f+\"/status\");a.isWifiClient=ko.pureComputed(function(){return\"STA\"===a.mode()||\"STA+AP\"===a.mode()});a.isWifiAccessPoint=ko.pureComputed(function(){return\"AP\"===a.mode()||\"STA+AP\"===a.mode()});a.fullMode=ko.pureComputed(function(){switch(a.mode()){case \"AP\":return\"Access Point (AP)\";\n"
  "case \"STA\":return\"Client (STA)\";case \"STA+AP\":return\"Client + Access Point (STA+AP)\"}return\"Unknown (\"+a.mode()+\")\"})}function h(a){ko.mapping.fromJS(a,{},this)}function k(){var a=this;a.results=ko.mapping.fromJS([],{key:function(a){return ko.utils.unwrapObservable(a.bssid)},create:function(a){return new h(a.data)}});a.remoteUrl=f+\"/scan\";a.fetching=ko.observable(!1);a.update=function(b){b=void 0===b?function(){}:b;a.fetching(!0);$.get(a.remoteUrl,function(b){ko.mapping.fromJS(b,a.results);a.results.sort(function(a,\n"
  "b){return a.ssid()===b.ssid()?a.rssi()<b.rssi()?1:-1:a.ssid()<b.ssid()?-1:1})},\"json\").always(function(){a.fetching(!1);b()})}}function g(){d.call(this,{ssid:\"\",pass:\"\",firmware:\"-\",protocol:\"-\",espflash:\"\",version:\"0.0.0\"},f+\"/config\")}function l(){var a=this;a.config=new g;a.status=new e;a.scan=new k;a.initialised=ko.observable(!1);a.updating=ko.observable(!1);a.scanUpdating=ko.observable(!1);a.bssid=ko.observable(\"\");a.bssid.subscribe(function(b){for(var c=0;c<a.scan.results().length;c++){var d=\n"
  "a.scan.results()[c];if(b===d.bssid()){a.config.ssid(d.ssid());break}}});var b=null,c=null;a.start=function(){a.updating(!0);a.config.update(function(){a.status.update(function(){a.initialised(!0);b=setTimeout(a.update,5E3);a.updating(!1)})})};a.update=function(){a.updating()||(a.updating(!0),null!==b&&(clearTimeout(b),b=null),a.status.update(function(){b=setTimeout(a.update,5E3);a.updating(!1)}))};var d=!1;a.startScan=function(){a.scanUpdating()||(d=!0,a.scanUpdating(!0),null!==c&&(clearTimeout(c),\n"
  "c=null),a.scan.update(function(){d&&(c=setTimeout(a.startScan,3E3));a.scanUpdating(!1)}))};a.stopScan=function(){d=!1;a.scanUpdating()||null===c||(clearTimeout(c),c=null)};a.wifiConnecting=ko.observable(!1);a.status.mode.subscribe(function(b){\"STA+AP\"!==b&&\"STA\"!==b||a.wifiConnecting(!1);\"STA+AP\"===b||\"AP\"===b?a.startScan():a.stopScan()});a.saveNetworkFetching=ko.observable(!1);a.saveNetworkSuccess=ko.observable(!1);a.saveNetwork=function(){\"\"===a.config.ssid()?alert(\"Please select network\"):(a.saveNetworkFetching(!0),\n"
  "a.saveNetworkSuccess(!1),$.post(f+\"/savenetwork\",{ssid:a.config.ssid(),pass:a.config.pass()},function(){a.saveNetworkSuccess(!0);a.wifiConnecting(!0)}).fail(function(){alert(\"Failed to save WiFi config\")}).always(function(){a.saveNetworkFetching(!1)}))};a.turnOffAccessPointFetching=ko.observable(!1);a.turnOffAccessPointSuccess=ko.observable(!1);a.turnOffAccessPoint=function(){a.turnOffAccessPointFetching(!0);a.turnOffAccessPointSuccess(!1);$.post(f+\"/apoff\",{},function(b){console.log(b);\"\"!==a.status.ipaddress()?\n"
  "setTimeout(function(){window.location=\"http://\"+a.status.ipaddress();a.turnOffAccessPointSuccess(!0)},3E3):a.turnOffAccessPointSuccess(!0)}).fail(function(){alert(\"Failed to turn off Access Point\")}).always(function(){a.turnOffAccessPointFetching(!1)})}}var f=\"http://\"+window.location.hostname;d.prototype.update=function(a){a=void 0===a?function(){}:a;var b=this;b.fetching(!0);$.get(b.remoteUrl,function(a){ko.mapping.fromJS(a,b)},\"json\").always(function(){b.fetching(!1);a()})};e.prototype=Object.create(d.prototype);\n"
  "e.prototype.constructor=e;g.prototype=Object.create(d.prototype);g.prototype.constructor=g;$(function(){var a=new l;ko.applyBindings(a);a.start()})})();function scaleString(d,e,h){return(parseInt(d)/e).toFixed(h)};\n";
