# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build OpenEVSE GUI

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

  pull_request:
    paths:
      - gui-v2
      - gui-tft/*

jobs:
  build:
    name: Build the static GUI files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          ref: ${{ github.head_ref }}
          token: ${{ secrets.DEPENDABOT_PAT }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Set up Node JS
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd gui-v2
          npm install

      - name: Build GUI
        run: |
          cd gui-v2
          npm run build

      - name: Delete the existing pre-built GUI files
        run: |
          rm -fr src/lcd_static
          rm -f src/web_static/*.h

      - name: Run PlatformIO
        run: |
          pio run
          git status

      - name: Push any changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update of pre-built GUI files"
