# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build OpenEVSE divert simulator

# Allow dependabot to update checks
permissions:
  checks: write
  actions: write
  contents: write
  issues: read
  pull-requests: write

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and test divert_sim
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          path: OpenEVSE_WiFi

      - uses: ammaraskar/gcc-problem-matcher@master

      - name: Install native build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libavahi-client-dev libavahi-common-dev

      - name: Build the simulator
        run: |
          python -m pip install --upgrade pip platformio
          cd OpenEVSE_WiFi
          python -m platformio run -e native_simulator

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: divert_sim
          path: OpenEVSE_WiFi/.pio/build/native_simulator/program

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install -r OpenEVSE_WiFi/divert_sim/requirements.txt

      - name: run tests
        run: |
          cd OpenEVSE_WiFi/divert_sim
          mkdir -p output
          pytest -v --color=yes --code-highlight yes --junit-xml=output/test_results.xml

      - name : Upload test results
        uses: actions/upload-artifact@v7
        with:
          name: sim_test_results
          path: |
            OpenEVSE_WiFi/divert_sim/output
            OpenEVSE_WiFi/divert_sim/view.html

      - name: Publish Simulator Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: OpenEVSE_WiFi/divert_sim/output/*.xml
          check_name: Simulator Tests
